Drop unicode superscript 2
The "Build Generated Workspaces" CI step complains:
    error: Submission.lean:10:19: unexpected token '²'; expected ']'
So this attempts to fix that